version: "3"

services:
  TVShows-tracker:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: fullstack
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
